# Site settings
title: Míša Novotná - Dula
tagline: Vítejte u služeb asistence v těhotenství
author: Michaela Novotná
first_button_text: 'Kontaktuj mě'
first_button_url: '#contact'
header_img: /img/test4.jpg
home_menu_text: Dula Míša Novotná
description: Chápeme, že těhotenství a období po porodu mohou být časem plným smíšených emocí a výzev. Proto jsme zde, abychom vám nabídli podporu, vedení a pomocnou ruku na této krásné, přesto náročné cestě.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Theme customization
primary: '#c09cb3'
dark: '#222'

# Contact details
email: dulamisa@duly.cz
telephone_number: 773568233
whatsapp_number: 
twitter_username: 
github_username:
instagram_username: 
facebook_username: misadula
linkedin_username: 

# Data collections
collections:
  blocks:
    output: false
  gallery:
    output: false

# Build settings
markdown: kramdown

exclude:
  - serve
  - README.md
  - LICENCE

