# Site settings
title: Míša Novotná - Dula
tagline: Your Favorite Source of Free Bootstrap Themes
author: 
first_button_text: 'Kontaktuj mě'
first_button_url: '#about'
header_img: /img/header.jpg
home_menu_text: Míša Dula
description: Start Bootstrap can help you build better websites using the Bootstrap CSS framework! Just download your template and start going, no strings attached!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Theme customization
primary: '#F05F40'
dark: '#222'

# Contact details
email: 
telephone_number: 773568233
whatsapp_number: 
twitter_username: 
github_username: volny
instagram_username: 
facebook_username: misadula
linkedin_username: 

# Data collections
collections:
  blocks:
    output: false
  gallery:
    output: false

# Build settings
markdown: kramdown

exclude:
  - serve
  - README.md
  - LICENCE

